---
- name: this playbook for vars variables
  hosts: all
  vars files: demo.yml
  tasks: 
   - name: writing my first tasks example for the vars variables
     debug: 
       msg: "{my fisrt vars-variables}"
...