# my_playbook.yml
---
- name: Playbook using vars files
  hosts: your_target_hosts
  vars_files:
    - my_vars.yml

  tasks:
    - name: Display variable values
      debug:
        var: my_variable1

    - name: Another task using a different variable
      debug:
        var: my_variable2
...