---
- name: this playbook for vars files variables
  hosts: all
  vars files: demo.yml
  tasks: 
   - name: writing my first tasks example for the vars files variables
     debug: 
       msg: "{my fisrt vars-variables}"
...